// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBu_4C_P0vi7RNR7-wFjIFpHHrpxqdgmBA',
    appId: '1:316157001768:web:6d16a833cfa219e09c751d',
    messagingSenderId: '316157001768',
    projectId: 'jainebook',
    authDomain: 'jainebook.firebaseapp.com',
    storageBucket: 'jainebook.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBPTUk6GxEATHWOPqLxvD-GJWZVMuQFAk',
    appId: '1:316157001768:android:ecd1d42f38e7e97a9c751d',
    messagingSenderId: '316157001768',
    projectId: 'jainebook',
    storageBucket: 'jainebook.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXdLCAa7ASX-nx6rfw46lU2AOIc5fDUhQ',
    appId: '1:316157001768:ios:1fbc23b2f9b0301c9c751d',
    messagingSenderId: '316157001768',
    projectId: 'jainebook',
    storageBucket: 'jainebook.firebasestorage.app',
    iosBundleId: 'shubhamjain.space.jainebook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXdLCAa7ASX-nx6rfw46lU2AOIc5fDUhQ',
    appId: '1:316157001768:ios:1fbc23b2f9b0301c9c751d',
    messagingSenderId: '316157001768',
    projectId: 'jainebook',
    storageBucket: 'jainebook.firebasestorage.app',
    iosBundleId: 'shubhamjain.space.jainebook',
  );
}
